### ISSUE TITLE
Verdeling van debiet bij splitsingen afhankelijk maken van diameters leidingen 

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/sewerage-designer#21]
Met name relevant bij bestaande leidigingen
Is bij ontwerpleidingen complex omdat debiet dan afhankelijk wordt van diameter, terwijl diameter afhankelijk is van debiet

**Comment by Overmeen** [comment]
Moved to Trello https://trello.com/b/wHgd3Jq6
