### ISSUE TITLE
issues moved to Trello https://trello.com/b/wHgd3Jq6

### ISSUE THREAD

**Issue by Overmeen** [nens/sewerage-designer#56]
https://trello.com/b/wHgd3Jq6

**Comment by NyakudyaA** [comment]
Please also fix the plugin homepage link in metadata.txt to reference this repo rather than the website unless you redirect users to a specific page on the website that deals with the plugin. Trello assumes you need to create a login to view the issues, Pleas e rather stick with github

**Comment by Overmeen** [comment]
Hi @NyakudyaA, are you a QGIS moderator? Is it required for the moderators to see the open tickets?

I will update the metadata.txt as you mentioned.

Will our plug-in get a public version after these changes? We would like to have a public version by the 6th of April if possible, as we have an important conference at that day.

**Comment by NyakudyaA** [comment]
Yes, I manage plugin approvals with other members of the QGIS community. It is required for users to be able to see the source code, file tickets and submit pull requests to improve your plugin. This will also ensure traction on your plugin etc.

If the changes are effected. i will approve the plugin

**Comment by Overmeen** [comment]
Great thanks. I will move the issues back to our repo

**Comment by Overmeen** [comment]
@NyakudyaA the issues have been added back to the repo

**Comment by NyakudyaA** [comment]
Please update the version on the plugin repository, it still references the old link

**Comment by Overmeen** [comment]
@NyakudyaA updated!
